postgres:
  user: $PG_USER
  pass: $PG_PASS
  addr: theprime_dev-postgres-1:5432
  name: theprime

redis:
  addr: theprime_dev-redis-1:6379
  db: 0

nats:
  addr: nats://theprime_dev-nats-1:4222

ton:
  deposit_wallet: $DEPOSIT_WALLET

fragment:
  wallet_seed: $WALLET_SEED
  auth_cookie: 'stel_ssid=wefweffewfwefwf_fwefwefew; stel_dt=-1233; stel_token=iwef9hf923hf239fh29fh2f92hf92hf9fhfh8fh298hf329f; stel_ton_token=FHWE(UHewuhhu*FUHEW*FHwhufwhuefeiwufhuwif-IgREGxgtqXBmKGgBxOz1WSnkqKIQ17-owenfpw9ufpe9ufNKJNISEJFNLEWIFNnfewjkfnijfw-'
  min_balance: 5.0
  chatGifts: 0

referral:
  total_bonus: 10
  levels: [50, 25, 15, 10]

workers:
  webhook: 2
  users: 2
  tasks: 2
  chats: 2
  checks: 2

bot:
  token: $BOT_TOKEN
  rate_msg_limit: 25
  rate_api_limit: 25

miniapp:
  webapp_url: https://miniapp-dev.getprime.me
  miniapp_url: https://t.me/NotYourPrimeDevBot/get
  support_url: https://t.me/The_Prime_Support_bot
  hello_image: https://miniapp.getprime.me/prime_640x360.JPEG
  en:
    webapp_button: üéÅ Get Prime
    support_button: ü§ñ Support
    hello_text: |
      <b>Welcome!</b>

      Earn <b>Telegram Stars</b> or <b>Telegram Premium</b> by completing simple tasks in this bot.

      How It Works:
      1. Select a task from the list
      2. Follow the instructions and complete it
      3. Get rewarded for your efforts

      Start now and enjoy exclusive Telegram benefits!
  ru:
    webapp_button: üéÅ –ü–æ–ª—É—á–∏—Ç—å –ø—Ä–µ–º–∏—É–º
    support_button: ü§ñ –ü–æ–¥–¥–µ—Ä–∂–∫–∞
    hello_text: |
      <b>–î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å!</b>

      –í —ç—Ç–æ–º –±–æ—Ç–µ –≤—ã –º–æ–∂–µ—Ç–µ –≤—ã–ø–æ–ª–Ω—è—Ç—å –ø—Ä–æ—Å—Ç—ã–µ –∑–∞–¥–∞–Ω–∏—è –∏ –ø–æ–ª—É—á–∞—Ç—å <b>Telegram Stars</b> –∏–ª–∏ <b>Telegram Premium</b> –≤ –∫–∞—á–µ—Å—Ç–≤–µ –Ω–∞–≥—Ä–∞–¥—ã.  

      –ö–∞–∫ —ç—Ç–æ —Ä–∞–±–æ—Ç–∞–µ—Ç?  
      1. –í—ã–±–µ—Ä–∏—Ç–µ –∑–∞–¥–∞–Ω–∏–µ –∏–∑ —Å–ø–∏—Å–∫–∞.  
      2. –í—ã–ø–æ–ª–Ω–∏—Ç–µ –µ–≥–æ —Å–æ–≥–ª–∞—Å–Ω–æ –∏–Ω—Å—Ç—Ä—É–∫—Ü–∏–∏.  
      3. –ü–æ–ª—É—á–∏—Ç–µ –∑–∞—Å–ª—É–∂–µ–Ω–Ω–æ–µ –≤–æ–∑–Ω–∞–≥—Ä–∞–∂–¥–µ–Ω–∏–µ!  

      –ù–∞—á–Ω–∏—Ç–µ –ø—Ä—è–º–æ —Å–µ–π—á–∞—Å –∏ –≤–æ—Å–ø–æ–ª—å–∑—É–π—Ç–µ—Å—å —ç–∫—Å–∫–ª—é–∑–∏–≤–Ω—ã–º–∏ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—è–º–∏ Telegram!
